/**
 * Scheduled Reports Engine
 *
 * In production, trigger these via:
 * - Vercel Cron Jobs (vercel.json)
 * - Railway cron tasks
 * - External scheduler hitting /api/cron/reports
 *
 * The /api/cron/reports route is protected by a CRON_SECRET header.
 */

import connectDB from "@/lib/db/connection";
import { AttendanceDay, Employee, Organization } from "@/lib/db/models";
import { sendEmail } from "@/lib/notifications/email";

export interface ScheduledReportConfig {
  organizationId: string;
  type: "DAILY" | "WEEKLY" | "MONTHLY";
  recipientEmails: string[];
}

export async function generateDailySummaryReport(orgId: string): Promise<void> {
  await connectDB();

  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  const dateKey = yesterday.toISOString().split("T")[0];

  const org = await Organization.findById(orgId).lean();
  if (!org) return;

  const [totalEmployees, dayRecords] = await Promise.all([
    Employee.countDocuments({ organizationId: orgId, status: "ACTIVE" }),
    AttendanceDay.find({ organizationId: orgId, dateKey }).lean(),
  ]);

  const present = dayRecords.filter((d) =>
    ["PRESENT", "LATE", "OVERTIME"].includes(d.status)
  ).length;
  const absent = dayRecords.filter((d) => d.status === "ABSENT").length;
  const late = dayRecords.filter((d) => d.status === "LATE").length;
  const onLeave = dayRecords.filter((d) => d.status === "ON_LEAVE").length;

  const { subject, html } = buildDailyReportEmail(org.name, dateKey, {
    totalEmployees,
    present,
    absent,
    late,
    onLeave,
    attendancePct: totalEmployees > 0 ? Math.round((present / totalEmployees) * 100) : 0,
  });

  // Send to HR contacts
  if (org.hrContactName && org.contactEmail) {
    await sendEmail({ to: org.contactEmail, subject, html });
  }
}

function buildDailyReportEmail(
  orgName: string,
  date: string,
  stats: {
    totalEmployees: number;
    present: number;
    absent: number;
    late: number;
    onLeave: number;
    attendancePct: number;
  }
): { subject: string; html: string } {
  const subject = `${orgName} — Daily Attendance Summary for ${date}`;
  const html = `
    <!DOCTYPE html>
    <html>
    <body style="font-family: system-ui, sans-serif; background: #f9fafb; padding: 40px 20px;">
      <div style="max-width: 520px; margin: 0 auto; background: white; border-radius: 16px; padding: 32px; border: 1px solid #e5e7eb;">
        <h2 style="margin: 0 0 4px; color: #111827;">Daily Attendance Summary</h2>
        <p style="color: #6b7280; margin: 0 0 24px; font-size: 14px;">${orgName} · ${date}</p>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px;">
          <div style="background: #f0fdf4; border-radius: 12px; padding: 16px; text-align: center;">
            <div style="font-size: 28px; font-weight: bold; color: #16a34a;">${stats.present}</div>
            <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Present</div>
          </div>
          <div style="background: #fef2f2; border-radius: 12px; padding: 16px; text-align: center;">
            <div style="font-size: 28px; font-weight: bold; color: #dc2626;">${stats.absent}</div>
            <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Absent</div>
          </div>
          <div style="background: #fffbeb; border-radius: 12px; padding: 16px; text-align: center;">
            <div style="font-size: 28px; font-weight: bold; color: #d97706;">${stats.late}</div>
            <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Late</div>
          </div>
          <div style="background: #eff6ff; border-radius: 12px; padding: 16px; text-align: center;">
            <div style="font-size: 28px; font-weight: bold; color: #2563eb;">${stats.onLeave}</div>
            <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">On Leave</div>
          </div>
        </div>

        <div style="background: #f9fafb; border-radius: 12px; padding: 16px; text-align: center;">
          <div style="font-size: 32px; font-weight: bold; color: #4f46e5;">${stats.attendancePct}%</div>
          <div style="font-size: 13px; color: #6b7280;">Overall Attendance Rate</div>
          <div style="font-size: 12px; color: #9ca3af; margin-top: 4px;">${stats.present} of ${stats.totalEmployees} employees</div>
        </div>

        <p style="font-size: 12px; color: #9ca3af; margin-top: 24px; text-align: center;">
          Generated by Chekin Attendance Management · <a href="${process.env.NEXT_PUBLIC_APP_URL}/admin" style="color: #4f46e5;">View Dashboard</a>
        </p>
      </div>
    </body>
    </html>
  `;

  return { subject, html };
}
